dependencies {
    implementation 'org.slf4j:jul-to-slf4j'
    implementation 'ch.qos.logback:logback-core'
    implementation 'ch.qos.logback:logback-classic'

    compile group: "org.eclipse", name: "osgi", version: equinoxVersion, configuration: "compile", ext: "jar"
    implementation group: 'org.eclipse.birt.runtime.3_7_1', name: 'org.eclipse.osgi.services' , version: osgiServicesVersion
    implementation group: 'org.eclipse.osgi', name: 'org.eclipse.equinox.cm', version: equinoxCmVersion

    testImplementation project(':test:org.eclipse.virgo.test.stubs')

    implementation project(':util:org.eclipse.virgo.util.io')
    implementation project(':util:org.eclipse.virgo.util.osgi')
    implementation project(':medic:org.eclipse.virgo.medic')
}
