dependencies {

    compile group: "org.eclipse", name: "osgi", version: equinoxVersion, configuration: "compile", ext: "jar"
    implementation group: 'org.eclipse.birt.runtime.3_7_1', name: 'org.eclipse.osgi.services' , version: osgiServicesVersion
    implementation group: 'org.eclipse.equinox', name: 'org.eclipse.equinox.region', version: equinoxRegionVersion

    compile project(':util:org.eclipse.virgo.util.osgi.manifest')
    compile project(':medic:org.eclipse.virgo.medic')
    compile project(':nano:org.eclipse.virgo.nano.core')
    compile project(':kernel:org.eclipse.virgo.kernel.artifact')

    aspect project(':nano:org.eclipse.virgo.nano.core')
}
