dependencies {
    implementation 'javax.servlet:javax.servlet-api'

    implementation files('../../local-dependencies/org.apache.catalina_8.5.16.jar')
    //implementation group: "org.eclipse.virgo.mirrored", name: "org.apache.catalina", version: apacheCatalinaVersion, configuration: "compile", ext: "jar"
    
    implementation files('../../local-dependencies/org.apache.tomcat.api_8.5.16.jar')
    //implementation group: "org.eclipse.virgo.mirrored", name: "org.apache.tomcat.api", version: apacheCatalinaVersion, configuration: "compile", ext: "jar"
    
    implementation group: "org.apache.openwebbeans", name: "openwebbeans-tomcat7", version: apacheOpenwebbeansTomcat7Version, configuration: "compile", ext: "jar"
}
