dependencies {
    implementation 'javax.transaction:javax.transaction-api'
    implementation 'org.eclipse.persistence:org.eclipse.persistence.core'

    implementation files('../../local-dependencies/org.apache.openejb.core_4.5.2.virgo-3.jar')
    //compile group: "org.eclipse.virgo.mirrored", name: "org.apache.openejb.core", version: apacheOpenejbCoreVersion, configuration: "compile", ext: "jar"
    implementation files('../../local-dependencies/org.apache.openejb.loader_4.5.2.jar')
    //compile group: "org.eclipse.virgo.mirrored", name: "org.apache.openejb.loader", version: apacheOpenejbVersion, configuration: "compile", ext: "jar"
    
    implementation 'org.hibernate:hibernate-core:4.1.0.Final'
}
