dependencies {
	implementation 'junit:junit'

	compile group: "org.eclipse", name: "osgi", version: equinoxVersion, configuration: "compile", ext: "jar"

	compile project(':util:org.eclipse.virgo.util.common')
	compile project(':util:org.eclipse.virgo.util.parser.launcher')

	compile project(':test:org.eclipse.virgo.test.stubs')
	compile project(':test:org.eclipse.virgo.test.launcher')
}
