dependencies {
    implementation 'javax.ejb:javax.ejb-api'
    implementation 'javax.persistence:javax.persistence-api'

    implementation 'javax.enterprise:cdi-api'
    compile group: "org.glassfish", name: "javax.faces", version: glassfishComSunFacesVersion, configuration: "compile", ext: "jar"
    compile group: "org.apache.openwebbeans", name: "openwebbeans-impl", version: apacheOpenwebbeansVersion, configuration: "compile", ext: "jar"
}
