dependencies {
    compile group: "org.eclipse", name: "osgi", version: equinoxVersion, configuration: "compile", ext: "jar"
    implementation group: 'org.eclipse.equinox', name: 'org.eclipse.equinox.region', version: equinoxRegionVersion

    //compile group: "org.eclipse.virgo.mirrored", name: "org.eclipse.gemini.management", version: geminiManagementVersion, configuration: "compile", ext: 'jar'
    implementation files('../../local-dependencies/org.eclipse.gemini.management-1.0.5.RELEASE.jar')
}
